services:
  backend:
    image: stenknz/rss-pro-backend:latest
    container_name: rss-reader-backend
    ports:
      - "8000:8000"
    volumes:
      - /volume1/Docker/rss-pro/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/rss.db
      - LOG_LEVEL=INFO
      - FULLTEXT_RSS_URL=http://fullfeedrss/extract.php
    restart: unless-stopped

  frontend:
    image: stenknz/rss-pro-frontend:latest
    container_name: rss-reader-frontend
    ports:
      - "8383:80"
    depends_on:
      - backend
    restart: unless-stopped

  fullfeedrss:
    image: heussd/fivefilters-full-text-rss:latest
    container_name: rss-reader-fulltext
    mem_limit: 512m
    restart: unless-stopped
    environment:
      - FTR_ADMIN_PASSWORD=
    volumes:
      - ftr-cache:/var/www/html/cache/rss

volumes:
  ftr-cache:
